version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
  job:
    build: .
    command: bash -c "bundle exec sidekiq"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  pg_data:
  redis_data:
  gem_cache:
  node_modules:
  bundle: